apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::371068675683:role/kubernetes-cluster2023092818031276450000000c
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::371068675683:user/admin
      username: admin
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::371068675683:role/kubernetes-cluster2023092818031276450000000c\n  username: system:node:{{EC2PrivateDNSName}}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-09-28T18:04:08Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1145","uid":"22377412-bd21-4de9-8bfd-d1d827a191ae"}}
  creationTimestamp: "2023-09-28T18:04:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "30456"
  uid: 22377412-bd21-4de9-8bfd-d1d827a191ae
