apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  ports:
    - port: {{ .Values.port.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.port.containerPort }}
  selector:
    app: {{ .Values.app.name }}
